#! /bin/sh
set -e

cmd=$0
arg1=$1

if ! which update-emboot >/dev/null 2>&1; then
    PATH=$PATH:/usr/local/bin:/usr/local/sbin
    export PATH
    which update-emboot >/dev/null 2>&1 || exit 0
fi

if type systemd-detect-virt >/dev/null 2>&1 &&
   systemd-detect-virt --quiet --container; then
	exit 0
fi

set -- $DEB_MAINT_PARAMS
mode="${1#\'}"
mode="${mode%\'}"
case $cmd:$mode:$DPKG_MAINTSCRIPT_PACKAGE in
    */postinst.d/*::*|*/postinst.d/*:configure:*)
        exec update-emboot
	;;
    */postrm.d/*::*|*/postrm.d/*:remove:*)
        exec update-emboot -i
	;;
    */post-update.d/*:*:|*/post-update.d/*:*:*)
        krel=$arg1
        exec update-emboot ${krel:+-k "$krel"}
        ;;
esac

exit 0
