#! /bin/bash

exec 3>&1 1>&2

set -e

. /etc/efi-measured-boot/config
. "$APPDIR"/functions

setup_tmp_dir

cleanup() {
    teardown_tmp_dir
}

trap cleanup EXIT

read_counter >counter
create_provision_context
main_loader="$EFI_MOUNT"/"$(echo "EFI/$OS_SHORT_NAME/$OS_SHORT_NAME.EFI" | tr a-z A-Z)"
old_loader="$EFI_MOUNT"/"$(echo "EFI/$OS_SHORT_NAME/${OS_SHORT_NAME}_OLD.EFI" | tr a-z A-Z)"
seal_to_efi_app /vmlinuz "$main_loader"
seal_to_efi_app /vmlinuz.old "$old_loader"

exit 0
