#! /bin/bash

cmd=$0

exec 3>&1 1>&2

set -e

[ -r /etc/efi-measured-boot/config ] && . /etc/efi-measured-boot/config
if [[ $cmd = ./* ]]; then APPDIR=.; fi
. "${APPDIR:-.}"/functions
. "${APPDIR:-.}"/bash_functions

emboot_kernels=( $(list_emboot_kernel_versions) )

read_emboot_efi_apps
