#! /bin/bash

cmd=$0
devnode=$1

exec 3>&1 1>&2

[ -r /etc/efi-measured-boot/config ] && . /etc/efi-measured-boot/config
if [[ $cmd = ./* ]]; then APPDIR=.; fi
. "${APPDIR:-.}"/functions
. "${APPDIR:-.}"/bash_functions

set -e

parentdevices=( $(lsblk -s -t $devnode -o UUID -n -r | grep '.') )
parentdevicenodes=( $(lsblk -p -s -t $devnode -o NAME -n -r | grep '.') )
OLDIFS=$IFS
IFS=$'\n'
crypttabentries=( $(sed -e 's/#.*//' /etc/crypttab | grep -E "UUID=($(buildre ${parentdevices[@]}))" || true) )
if (( ${#crypttabentries[@]} == 0 )); then
    echo 'crypttab entry not found via UUID; trying node' 1>&2
    crypttabentries=( $(sed -e 's/#.*//' /etc/crypttab | grep -E "$(buildre ${parentdevicenodes[@]})" || true) )
fi
IFS=$OLDIFS
if (( ${#crypttabentries[@]} == 0 )); then
    echo 'crypttab entry not found' 1>&2
    exit 1
fi
if (( ${#crypttabentries[@]} > 1 )); then
    echo 'filesystem in multiple crypttab entries unsupported' 1>&2
    IFS=$'\n'; echo "${crypttabentries[*]}"
    exit 1
fi
cryptdev=( ${crypttabentries[0]} )

IFS=' '
echo "${cryptdev[*]}" 1>&3
