#! /bin/sh

# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Kyle R. Rose

set -e

cmd=$0
arg1=$1

which update-emboot >/dev/null 2>&1 || exit 0
[ -e /etc/efi-measured-boot/configured ] || exit 0

if type systemd-detect-virt >/dev/null 2>&1 &&
   systemd-detect-virt --quiet --container; then
	exit 0
fi

eval set -- $DEB_MAINT_PARAMS
mode="${1#\'}"
mode="${mode%\'}"
case $cmd:$mode:$DPKG_MAINTSCRIPT_PACKAGE in
    */post-update.d/*:*:|*/post-update.d/*:*:*)
        krel=$arg1
        set +e
        update-emboot ${krel:+-k "$krel"} ${EMBOOT_KERNEL_HOOK_NO_SEAL:+-S}
        rc=$?
        if [ "$rc" -ne 0 ]; then
            echo "update-emboot failed with exit code $rc" >&2
            echo "WARNING: emboot EFI entries may be unbootable!" >&2
        fi
        ;;
esac

exit 0
