#! /bin/sh
PREREQ=""
prereqs()
{
	echo "$PREREQ"
}

case $1 in
	prereqs)
		prereqs
		exit 0
		;;
esac

. /usr/share/initramfs-tools/hook-functions

for i in createprimary load startauthsession policypcr policynv unseal flushcontext; do
    copy_exec /usr/bin/tpm2_$i /usr/bin
done
copy_exec /usr/lib/x86_64-linux-gnu/libtss2-tcti-device.so.0 /usr/lib/x86_64-linux-gnu

mkdir -p $DESTDIR/etc/efi-measured-boot
for i in config functions; do
    cp /etc/efi-measured-boot/$i $DESTDIR/etc/efi-measured-boot
done

force_load tpm_tis
force_load tpm_crb

# Hopefully this codepages/charsets is universal
force_load vfat
force_load nls_cp437
force_load nls_ascii
