#! /bin/sh
PREREQ=""
prereqs()
{
	echo "$PREREQ"
}

case $1 in
	prereqs)
		prereqs
		exit 0
		;;
esac

. /usr/share/initramfs-tools/hook-functions

for i in createprimary flushcontext load pcrread policynv policypcr startauthsession unseal; do
    copy_exec /usr/bin/tpm2_$i /usr/bin
done
copy_exec /usr/lib/x86_64-linux-gnu/libtss2-tcti-device.so.0 /usr/lib/x86_64-linux-gnu
copy_exec /usr/bin/jq /usr/bin

mkdir -p "$DESTDIR"/etc/efi-measured-boot
cp /etc/efi-measured-boot/config "$DESTDIR"/etc/efi-measured-boot/

. /etc/efi-measured-boot/config
mkdir -p "$DESTDIR/$APPDIR"
cp "$APPDIR"/functions "$DESTDIR/$APPDIR/"

force_load tpm_tis
force_load tpm_crb

# Hopefully this codepage/charset combination is universal
force_load vfat
force_load nls_cp437
force_load nls_ascii
